services:
  jenkins:
    image: adlatif/nodejs-ci-cd-pipeline:jenkins
    pull_policy: if_not_present
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mounting Docker socket
    privileged: true
    networks:
      - ci_cd_network

  sonarqube:
    image: adlatif/nodejs-ci-cd-pipeline:sonarqube
    pull_policy: if_not_present
    container_name: sonarqube
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - ci_cd_network

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  ci_cd_network:
    driver: bridge
