sonarqube:
  image: adlatif/nodejs-ci-cd-pipeline:sonarqube
  container_name: sonarqube
  ports:
    - '9000:9000'
  environment:
    - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  volumes:
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_logs:/opt/sonarqube/logs
  networks:
    - ci_cd_network

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
