services:
  jenkins:
    image: adlatif/nodejs-ci-cd-pipeline:jenkins
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mounting Docker socket
    privileged: true

    networks:
      - ci_cd_network

  sonarqube:
    image: adlatif/nodejs-ci-cd-pipeline:sonarqube
    container_name: sonarqube
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - ci_cd_network

volumes:
  jenkins_data:

networks:
  ci_cd_network:
    driver: bridge
